#include "hal/adc_hal.h"
#include "hal/dtc_hal.h"
#include "hal/elc_hal.h"
#include "hal/gpt_hal.h"
#include "hal/spi_hal.h"
#include "hal_data.h"

#include "output_control.h"
#include "page.h"
#include "keyboard.h"
#include "oled.h"
#include "pid_control.h"

extern volatile uint8_t cur_cmp;
extern volatile uint8_t vol_cmp;
extern volatile uint8_t update_ui_state;
extern adc_data current_adc_data_buffer;

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    elc_init();
    gpt_init(&system_timer_ctrl, &system_timer_cfg);
    gpt_init(&output_timer_ctrl, &output_timer_cfg);
    gpt_init(&oled_timer_ctrl, &oled_timer_cfg);
    gpt_init(&adc_timer_ctrl, &adc_timer_cfg);
    adc_init();
    dtc_init();
    spi_init(&oled_spi_ctrl, &oled_spi_cfg);

    elc_start();
    gpt_start(&system_timer_ctrl);
    
    dtc_start();

    OLED_Init();
    page_init();
    output_state=0;
    gpt_start(&oled_timer_ctrl);

    gpt_start(&adc_timer_ctrl);
    adc_start();

    while (1)
    {
        if(cur_cmp && vol_cmp && output_state){
            cur_cmp = 0 ;
            vol_cmp = 0;
            PID_Control(current_page->pid);
        }
        if(update_ui_state){
            update_ui_state=0;
            current_page->update_ui();
        }
        Current_PID.Current=(current_adc_data_buffer.current[0]+current_adc_data_buffer.current[1])*3.3f/2048.0f;
        Voltage_PID.Current=(current_adc_data_buffer.voltage[0]+current_adc_data_buffer.voltage[1])*3.3f/2048.0f;

        dispatch_for_keys(current_page->key_handlers);
    }


    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif


#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
